Error on the master branch, and direct people to main. See #805 (#823)
See #805

The behavior is now:

$ ./emsdk install 2.0.0
****
Error: You appear to be using the `master` branch of emsdk.
We recently made the switch to using `main`
In order to continue to receive updates you will need to make the switch locally too.
For normal clones without any local branches simply running the following command should be enough:
  `git checkout main`
For more information see https://github.com/emscripten-core/emsdk/issues/805
****
$ echo $?
1

If you see this error, you are using master, and should switch to main,
which is where development now occurs.